### ISSUE TITLE
Admin asked for password even though logged in with SAML

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/user_saml#309]
### Steps to reproduce
1. Login as Admin user by SAML
2. let some time go by
3. make an administrative change (e.g. install an app)

### Actual behaviour
Admin gets asked for password confirmation before change can be applied.

### Expected behaviour
Basically that confirmation dialog is a good thing, but if the admin is logged in via SAML, they don't have a password to provide.
There should at least be some hint on the SAML config page that admins should store a generic password for those cases.

**Comment by schiessle** [comment]
Is this still the case... IIRC this was fixed long ago but I don't have a system to test it at the moment

**Comment by dugite-code** [comment]
@schiessle I'm still experiencing this with NC 24.0.4 and user_saml 5.0.2

**Comment by zroug** [comment]
I'm still experiencing this too on NC 24.0.4 and user_saml 5.0.2. However it only happens after a while of being logged in. Logging out and back in fixes this issue temporarily for me.

**Comment by fastlorenzo** [comment]
Same issue for me with 24.0.5

**Comment by pierreozoux** [comment]
same with 24.0.9

**Comment by GeorgeGedox** [comment]
This affects admins for administrative actions, ie. install an app but also the normal users that want to generate app passwords for use with 3rd party clients and apps.

I'm surprised this problem has gone unresolved since 2019, could someone have a look at this please?

**Comment by dugite-code** [comment]
@GeorgeGedox I'm sure this is actually an issue with Nextcloud itself as I've switched to Social login for OIDC and I'm also encountering this there. It looks like there was work done a long time ago on this: https://github.com/nextcloud/server/pull/7487 Judging by this it looks like the user backend is checked and if the user is 100% a SSO user then password confirmation is not required.

My user however is LINKED to my SSO therefore the user backend will never be SSO exclusive. This was true with both SAML and now with OIDC

**Comment by j007bond007** [comment]
This is an issue for me using SAML with Authentik, try to update a user's quota and it wont accept my pw

**Comment by blizzz** [comment]
> *EDIT: Looks like the social login app actually had implemented this as a fix on a per-user basis. https://github.com/zorn-v/nextcloud-social-login/blob/fac1c374c5afd84417aeb0236c71f4be1db2e224/lib/AppInfo/Application.php#L48

SAML backend does the same: https://github.com/nextcloud/user_saml/blob/master/lib/UserBackend.php#L493C11-L493C30

Those effected, are you using env mode or built-in saml mode?

**Comment by blizzz** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/43612 – oidc suffers as well and solution might be possible on server side. PR soon.

**Comment by LokeYourC3PH** [comment]
> Closing in favor of [nextcloud/server#43612](https://github.com/nextcloud/server/issues/43612) – oidc suffers as well and solution might be possible on server side. PR soon.

This still seems to be an issue actually, I use OIDC with linked/existing NextCloud users, and admins do get prompts for their passwords which in reality they should not need anymore.
